-- 코드를 입력하세요
SELECT D.HOUR, COUNT(O.DATETIME) AS COUNT
FROM ANIMAL_OUTS O, (SELECT (LEVEL - 1) AS HOUR
                     FROM   DUAL
                     CONNECT BY LEVEL < 25) D
WHERE TO_CHAR(O.DATETIME(+), 'HH24') = D.HOUR
GROUP BY D.HOUR
ORDER BY D.HOUR
